projet fil rouge/monProjetSymfony/src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CategorieRepository::class)]
class Categorie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $libelle_categorie = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $img_categorie = null;

    #[ORM\ManyToOne(targetEntity: self::class, inversedBy: 'categories')]
    private ?self $categorie_mere = null;

    /**
     * @var Collection<int, self>
     */
    #[ORM\OneToMany(targetEntity: self::class, mappedBy: 'categorie_mere')]
    private Collection $categories;

    /**
     * @var Collection<int, Article>
     */
    #[ORM\OneToMany(targetEntity: Article::class, mappedBy: 'categorie')]
    private Collection $articles;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getLibelleCategorie(): ?string
    {
        return $this->libelle_categorie;
    }

    public function setLibelleCategorie(string $libelle_categorie): static
    {
        $this->libelle_categorie = $libelle_categorie;

        return $this;
    }

    public function getImgCategorie(): ?string
    {
        return $this->img_categorie;
    }

    public function setImgCategorie(?string $img_categorie): static
    {
        $this->img_categorie = $img_categorie;

        return $this;
    }

    public function getCategorieMere(): ?self
    {
        return $this->categorie_mere;
    }

    public function setCategorieMere(?self $categorie_mere): static
    {
        $this->categorie_mere = $categorie_mere;

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(self $category): static
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
            $category->setCategorieMere($this);
        }

        return $this;
    }

    public function removeCategory(self $category): static
    {
        if ($this->categories->removeElement($category)) {
            // set the owning side to null (unless already changed)
            if ($category->getCategorieMere() === $this) {
                $category->setCategorieMere(null);
            }
        }

        return $this;
    }
    /**
     * @return Collection<int, Article>
     */
    public function getArticles(): Collection
    {
        return $this->articles;
    }

    public function addArticle(Article $article): static
    {
        if (!$this->articles->contains($article)) {
            $this->articles->add($article);
            $article->setCategorie($this);
        }

        return $this;
    }

    public function removeArticle(Article $article): static
    {
        if ($this->articles->removeElement($article)) {
            // set the owning side to null (unless already changed)
            if ($article->getCategorie() === $this) {
                $article->setCategorie(null);
            }
        }
        
        return $this;
    }
}

projet fil rouge/monProjetSymfony/templates/base.html.twig
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<title>
			{% block title %}Welcome!
			{% endblock %}
		</title>
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
		<link rel="stylesheet" href="../css/styles.css"/> 
        {% block stylesheets %}{% endblock %}
		{% block javascripts %}
			{% block importmap %}
				{{ importmap('app') }}
			{% endblock %}
		{% endblock %}

	</head>
	<div class="fond container-fluid m-o p-0">
		<div class="row">
			<div class="col-12">
				<body class="fond">

					{% include "navbar.html.twig" %}

					{% block body %}{% endblock %}
				</body>
			</div>
		</div>
	</div>


	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</html></body></html>

projet fil rouge/monProjetSymfony/templates/navbar.html.twig
                
                <header class= "d-flex m-0 p-0 " >
                    <nav class="navbar navbar-expand-lg">
                            <div class="container-fluid">
                                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                    <span class="navbar-toggler-icon"></span>
                                </button>
                                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                                        <li class="nav-item">
                                            <a class="nav-link titre" href="{{ path('app_accueil') }}">ACCUEIL</a>
                                        </li>                               
                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle titre" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            CATALOGUE
                                            </a>
                                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                                {# {% for categorie in categories %}
                                                    <li><a class="dropdown-item titre" href="">{{categorie.libelleCategorie}}</a></li>
                                                {% endfor %} #}
                                                <li><a class="dropdown-item titre" href="{{ path('app_details_categories',{id:'1'}) }}">Jeux Experts</a></li>
                                                <li><a class="dropdown-item titre" href="{{ path('app_details_categories',{id:'2'}) }}">Jeux d'Ambiance</a></li>
                                                <li><a class="dropdown-item titre" href="{{ path('app_details_categories',{id:'3'}) }}">Escape Games</a></li>
                                            </ul>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link titre" href="#">CONTACT</a>
                                        </li>
                                    </ul>                         
                                </div>                            
                            </div>                                                 
                        </nav> 
                        <div class="m-auto">  
                                <img
                                width= "194px"
                                height= "194px"
                                src="{{asset('img/logo.png')}}"
                                alt="Hazelshop_logo"
                                title="HAZELSHOP_LOGO">                           
                                </img>
                        </div>
                        <div class="d-flex align-items-center" >
                            <a href="{{ path("app_panier") }}" class="btn" title="panier">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-basket3-fill" viewBox="0 0 16 16">
                                 <path d="M5.757 1.071a.5.5 0 0 1 .172.686L3.383 6h9.234L10.07 1.757a.5.5 0 1 1 .858-.514L13.783 6H15.5a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H.5a.5.5 0 0 1-.5-.5v-1A.5.5 0 0 1 .5 6h1.717L5.07 1.243a.5.5 0 0 1 .686-.172zM2.468 15.426.943 9h14.114l-1.525 6.426a.75.75 0 0 1-.729.574H3.197a.75.75 0 0 1-.73-.574z"/>
                                 </svg>
                            </a>
                            <a class="btn" title="profil" href="{{ path('app_utilisateur') }}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                                <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                                <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
                                </svg>
                            </a>
                        </div>                              
                    </header> 
        </div>
        <div class="col-12">